### ISSUE TITLE
Translate Center for Internet Security Docker Benchmark 1.11 into XCCDF format

### ISSUE THREAD

**Issue by JJediny** [OpenSCAP/container-compliance#11]
Docker has produced a machine readable form (all be it pure bash scripts) of the [CIP 1.11 Benchmark](https://benchmarks.cisecurity.org/tools2/docker/CIS_Docker_1.11.0_Benchmark_v1.0.0.pdf) in their [Docker Security Workbench utility](https://github.com/docker/docker-bench-security)

Would it make sense to translate these into a STIG-like audit for Docker hosts/containers formatting them in XCCDF?
https://github.com/docker/docker-bench-security/tree/master/tests

**Comment by isimluk** [comment]
This seems like a sensible idea. Can you please file issue against OpenSCAP/scap-security-guide? That project encompasses all the SCAP policies being build the open source way. Also if you decide to contribute first bits, I am sure that guys will be more than happy to assist.

More info about project: https://www.open-scap.org/security-policies/scap-security-guide/
Opened issues https://github.com/OpenSCAP/scap-security-guide/issues
Mailing list to discuss stuff: https://lists.fedorahosted.org/admin/lists/scap-security-guide.lists.fedorahosted.org/

Thanks!
