### ISSUE TITLE
Need a way to provide custom CVE definitions URL

### ISSUE THREAD

**Issue by atgreen** [OpenSCAP/container-compliance#13]
The oscap-docker script hard codes the CVE definitions URL to "http://www.redhat.com/security/data/oval/com.redhat.rhsa-all.xml".  However, many users run containers in completely disconnected environments, where the internet is not accessible.   For users who mirror the Red Hat oval pulp repo in house  (with Satellite**, for instance) there should be a way to provide a custom URL for the CVE definitions file, ideally through a configuration file under /etc.

*\* https://access.redhat.com/documentation/en/red-hat-satellite/6.2/single/content-management-guide/#importing_the_red_hat_oval_repository

**Comment by matejak** [comment]
Please use the `atomic scan` functionality, as it is much more powerful. It even allows you to configure your URL in `/etc/oscapd/config.ini` after you `atomic install` the `openscap` scanning container.
See [the documentation](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/security_guide/sect-using_openscap_with_atomic) for greater detail.
Closing, as the project is obsolete.
