### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by shawndwells** [OpenSCAP/container-compliance#6]
`git clone && make` produces:

```
f9b7ab31ee50: Already exists 
Digest: sha256:a17f67ebf159d8c50a882c70db4f2cc6e8ebefce24e9a9877da39b1d6d3179af
Status: Downloaded newer image for docker.io/dduportal/bats:0.4.0
Usage of loopback devices is strongly discouraged for production use. Either use `--storage-opt dm.thinpooldev` or use `--storage-opt dm.no_warn_on_loop_devices=true` to suppress this warning.
1..5
not ok 1 We use the Centos linux version 7
# (in test file /app/tests/bats/check_oscap_image.bats, line 6)
#   `[ "${FOUND_CENTOS_VERSION}" == "VERSION_ID=\"${CENTOS_VERSION}\"" ]' failed
# docker: error while loading shared libraries: libsqlite3.so.0: cannot open shared object file: No such file or directory
not ok 2 Wget is installed
# (in test file /app/tests/bats/check_oscap_image.bats, line 10)
#   `docker run --entrypoint sh "${DOCKER_IMAGE_NAME}" -c "which wget"' failed with status 127
# docker: error while loading shared libraries: libsqlite3.so.0: cannot open shared object file: No such file or directory
not ok 3 OSCAP is installed and in version 1.1.1
# (in test file /app/tests/bats/check_oscap_image.bats, line 15)
#   `docker run --entrypoint sh "${DOCKER_IMAGE_NAME}" -c "which oscap"' failed with status 127
# docker: error while loading shared libraries: libsqlite3.so.0: cannot open shared object file: No such file or directory
not ok 4 docker-oscap script is installed and available in the Path
# (in test file /app/tests/bats/check_oscap_image.bats, line 22)
#   `docker run --entrypoint sh "${DOCKER_IMAGE_NAME}" -c "which docker-oscap"' failed with status 127
# docker: error while loading shared libraries: libsqlite3.so.0: cannot open shared object file: No such file or directory
not ok 5 We are in /data by default, and this is a data volume
# (in test file /app/tests/bats/check_oscap_image.bats, line 27)
#   `[ "$(docker run --entrypoint pwd ${DOCKER_IMAGE_NAME})" == "${WORKDIR_PATH}" ]' failed
# docker: error while loading shared libraries: libsqlite3.so.0: cannot open shared object file: No such file or directory
make: *** [test] Error 1
```

**Comment by shawndwells** [comment]
this is on RHEL 7

**Comment by isimluk** [comment]
@dduportal, could you please take a look? You perhaps know more about this bats stuff then I do.

**Comment by dduportal** [comment]
Hello !

No problem, here some starting points :
- First, [bats](https://github.com/sstephenson/bats) is just bash based. it's a convenience tool to create test with a [standard TAP output](https://testanything.org/).
  => In this issue, bash responds with an exitcode different from 0, so the tests are failing. We have to find why, I suppose this is an environement requirement I haven't thought of and we might address :)
- Second step : All tes test are failing with the same error message : 

```
docker: error while loading shared libraries: libsqlite3.so.0: \
    cannot open shared object file: No such file or directory
```

=> The common denominator is a call to docker exec command.

@shawndwells, could you try :
- Given you've already built the docker image (docker images has a "dduportal/oscap4docker" entry, as stated by dduportal/oscap4docker which should be changed to not use my namespace :) )
- Try to run a basic docker run command to print help, and gist us the results :

```
docker run -ti dduportal/oscap4docker
```
- If it has worked, try a "docker in docker command" which will run the docker client inside an isolated container instead you raw system :

```
docker -v $(which docker):$(which docker) \
  -v /var/run/docker.sock:/var/run/docker.sock \
  --entrypoint $(which docker) \
  dduportal/bats:0.4.0 \
    images
```

that should print the docker images list as seen inside this container

And tell us if it works.

If both are working, we'll tests more complicated commands.

**Comment by PasqualePuzio** [comment]
Hi,

I'm experiecing a similar issue.
The command docker run -ti dduportal/oscap4docker works well. Unfortunately the second command keeps returning the following error:

/usr/bin/docker: error while loading shared libraries: libapparmor.so.1: cannot open shared object file: No such file or directory

I'm trying to run the OpenSCAP docker container on Debian.
I'm pretty sure libapparmor is installed on my machine, so I don't know what to do.

Could you please help?

Thanks

**Comment by isimluk** [comment]
@PasqualePuzio, can you tell which executable is searching for libapparmor.so.1? Is it docker? Is it oscap? Is it something else?

**Comment by PasqualePuzio** [comment]
Hi @isimluk from the logs I would say it's docker

**Comment by isimluk** [comment]
Ok, then please proceed with reporting this against docker packaging in Debian. ;-)

**Comment by PasqualePuzio** [comment]
Hi @isimluk ,

thanks for your answer.

I'm sorry but I disagree. Docker works normally and I'm able to create and run any container except yours. Maybe there is an issue on Debian?

Thanks

**Comment by isimluk** [comment]
What is the exact part you disagree on? :-)

Am I correct assuming that this is the command that does not work on Debian?

```
docker -v $(which docker):$(which docker) \
  -v /var/run/docker.sock:/var/run/docker.sock \
  --entrypoint $(which docker) \
  dduportal/bats:0.4.0 \
    images
```

If yes you need to debug why. You can try another image and give it try. However, for container-compliance to work you need to have to be able to run docker command inside a container. Otherwise you would need to have openscap installed on the host.

**Comment by dduportal** [comment]
Hello !

I have recently updated the tests to fit to latest version of wether docker and openscap.
After re-enabling my personal CircleCI build, i can reproduce the problem localy and in Cirlce : https://circleci.com/gh/dduportal/container-compliance/1

Work in progress

**Comment by PasqualePuzio** [comment]
Any news?

**Comment by dduportal** [comment]
Hello !

I've sent a PR to the main repo: https://github.com/OpenSCAP/container-compliance/pull/10 

Can you try with my latest image here: https://hub.docker.com/r/dduportal/container-compliance/ (instead of dduportal/oscap4docker) ?
