### ISSUE TITLE
OpenSCAP reports not applicable for RHEL 7 Docker images/containers

### ISSUE THREAD

**Issue by user987654** [OpenSCAP/container-compliance#7]
I am tyring to run OpenSCAP against an RHEL 7 Docker image and am getting not applicable. In debug logs of Openscap it shows that the rpminfo probe crashed. 
Issue https://github.com/OpenSCAP/openscap/issues/105 was created with open scap as this seems to be related to the openscap offline mode. However thought of posting it here if it help

**Comment by mpreisler** [comment]
This is tracked as issue 105 in the OpenSCAP issue tracker.
