### ISSUE TITLE
unable to test on a certain image

### ISSUE THREAD

**Issue by tobowers** [OpenSCAP/container-compliance#9]
```
docker run -v $PWD:/results -v /var/run/docker.sock:/var/run/docker.sock openscap image-cve timgreen/ldap:latest --results /results/oval.xml --report /results/report.html
Error response from daemon: open /mnt/sda1/var/lib/docker/aufs/mnt/0813c656b47dc8d7553fe7c82ac056456d8a1ee0007d3dc94034ea1c79d37f95/.wh..wh.plnk/601.408156: operation not permitted
tar: This does not look like a tar archive
tar: Exiting with failure status due to previous errors
```

I'm investigating that image more. The reason I'm testing that specific one is that I think it should show a CVE violation (though I'm not sure).

**Comment by isimluk** [comment]
The message says that docker daemon is not able to acess that specified image. I think this issue is unrelated with oscap-docker, rather it is related to your specific deployment setup.

If I am right, You will run into the same error, if you execute

```
docker save timgreen/ldap:latest
```

instead of oscap-docker image-cve.

**Comment by tobowers** [comment]
@isimluk so actually no... you don't. However, it's not related to oscap... it's that the image was created with a very old docker.

I did notice using centos:5.11 (an image that has shellshock) that it passes all tests from here. So, this particular repo is only useful for RHEL I suppose?

**Comment by isimluk** [comment]
yes
